### ISSUE TITLE
Saved images differ from Tensorboard Images

### ISSUE THREAD

**Issue by xujin1184104394** [torchgan/torchgan#86] opened 2019-02-19 09:39 UTC
I implemented it exactly as in the example/ example, but it is particularly poor compared to the example display.Can I ignore any key details?

**Comment by avik-pal** [comment] 2019-02-19 09:41
Could you give some more details? Like which example

**Comment by xujin1184104394** [comment] 2019-02-19 09:57
Cycgan on 100 epoch 
![cyclegan](https://user-images.githubusercontent.com/32417689/53006116-93f79000-346f-11e9-83ef-398c58509e71.png)

AAEGAN training Cifar10 on 200epoch 
![aaeganon200epoch](https://user-images.githubusercontent.com/32417689/53006193-b4bfe580-346f-11e9-9d9d-ac8e3bfd5d54.png)

self-att-GAN 
![self-att-gan](https://user-images.githubusercontent.com/32417689/53006223-c43f2e80-346f-11e9-8415-171bea502792.png)

**Comment by avik-pal** [comment] 2019-02-19 10:02
Actually, this problem is with the generated images which are saved. I haven't been able to figure out the reason for this. However, when you are using tensorboard or visdom the images are properly displayed.

**Comment by avik-pal** [comment] 2019-02-19 10:13
Ah I think I have a solution. We need to change [this](https://github.com/torchgan/torchgan/blob/71cfb007e5003775c8cadbeed683ca375135ac3b/torchgan/logging/visualize.py#L475) function call. We need to pass a `normalize=True` argument.

**Comment by xujin1184104394** [comment] 2019-02-19 10:20
Is it so changed?
image = torchvision.utils.make_grid(image，normalize=True)

**Comment by xujin1184104394** [comment] 2019-02-20 01:46
I did not generate the Tensorboard file when I trained the network according to the example. Is it necessary for me to manually add the Tensorboard code to visualize it?

**Comment by avik-pal** [comment] 2019-02-20 05:29
IMO, it is. Tensorboard results have always been accurate. So this way we can ensure that the problem is indeed in the generated images that were saved. Otherwise, there can be issues like mode collapse, etc which are resulting in the bad samples.

**Comment by avik-pal** [comment] 2020-05-05 22:19
Fixed by #102

**Closed by avik-pal** 2020-05-05 22:19 UTC
Labels: bug, good first issue
